baseURL               = "https://bioit.top"
languageCode          = "zh-CN"
title                 = "WebStack-Hugo 网址导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author          = "shenweiyan"
    description     = "WebStack-Hugo 网址导航主题 | Bio IT 爱好者"
    upload          = "https://github.com/shenweiyan/Bioit-top/blob/main/data/webstack.yml"
    about           = "https://weiyan.cc/discussions-10/"
    repository      = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad   = true
    textPreLoad     = "BioIT 爱好者"
    expandSidebar   = false
    logosPath       = "https://res.bioit.top/logos"
    defaultLogo     = "https://res.bioit.top/logos/default.webp"
    nightMode       = false
    yiyan           = true

[params.seo]
    baiduhmid       = ""
    baiduSiteVer    = ""
    tj51laid        = "3JHwtbgyvMReDNFU"
    tj51lack        = "3JHwtbgyvMReDNFU"
    GoogleAdsClient = ""

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "https://res.bioit.top/sites/bi-favicon.png"
    searchImageL      = "https://res.bioit.top/banner/bg-dna.jpg"
    searchImageD      = "https://res.bioit.top/banner/bg-dna.jpg"
    logoExpandLight   = "https://res.bioit.top/sites/bioit-expand-dark.png"
    logoExpandDark    = "https://res.bioit.top/sites/bioit-expand-light.png"
    logoCollapseLight = "https://res.bioit.top/sites/bi.png"
    logoCollapseDark  = "https://res.bioit.top/sites/bi.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [粤ICP备16023717号](http://beian.miit.gov.cn/) | [Netlify](https://app.netlify.com/) <br/> 本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：<a href="mailto:shen@weiyan.cc?subject=WebStack-Hugo网址导航意见反馈" target="_blank">shen@weiyan.cc</a> <br/><script id="LA-DATA-WIDGET" crossorigin="anonymous" charset="UTF-8" src="https://v6-widget.51.la/v6/3JHwtbgyvMReDNFU/quote.js?theme=#1690FF,#282A2D,#282A2D,#E87371,#FFFFFF,#1690FF,12&f=12&display=1,0,1,1,1,1,1,1"></script>'
